name: CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are checked out
          fetch-depth: 0    # Fetch all history for all branches and tags

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt install -y mpich libmpich-dev

      - name: List files for debugging
        run: ls -R 3rd_party/occa

      - name: Generate and Build
        run: |
          cd benchmark
          mkdir build
          cd build
          export KINETIX_PATH=$HOME/.local/kinetix
          cmake -DCMAKE_INSTALL_PREFIX=$KINETIX_PATH -DAMReX_GPU_BACKEND=NONE ..
          make VERBOSE=1 install
          cd $KINETIX_PATH
          export OCCA_CXX=mpic++
          bin/kinetix_bk --backend SERIAL --yaml-file kinetix/mechanisms/gri30.yaml --cimode 1
          rm -rf .cache/
          bin/kinetix_bk --backend SERIAL --yaml-file kinetix/mechanisms/gri30.yaml --cimode 1 --unroll-loops
